services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: "o1234"
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

# docker compose down
# docker compose up -d